module.exports = {
    onlyOwner: "Ownable: caller is not the owner",
    alreadyWhitelisted: "QuantArtsNFT: Account is already whitelisted",
    alreadyNotInWhitelist: "QuantArtsNFT: Account is already not in the whitelist",
    whitelistFull: "QuantArtsNFT: Whitelist is already full",
    accountIsNotInTheWhitelist: "QuantArtsNFT: Account is not in the whitelist",
    publicBeforeWhitelis: "QuantArtsNFT: Public timestamp is before whitelist timestamp",
    mintFinishBeforePublic: "QuantArtsNFT: Mint finish timestamp is before public timestamp",
    notWhitelisted: "QuantArtsNFT: Account is not in the whitelist",
    whiteListNotStarted: "QuantArtsNFT: Whitelist mint has not started yet",
    maximumMintedAmountReached: "QuantArtsNFT: Already minted amount is bigger than maxMintAmount",
    mintAmountZero: "QuantArtsNFT: Mint amount is zero",
    whitelistNotStarted: "QuantArtsNFT: Whitelist mint has not started yet",
    mintHasFinished: "QuantArtsNFT: Mint has finished",
    mintHasNotFinished: "QuantArtsNFT: Mint has not finished",
    sentPriceUnderpriced: "QuantArtsNFT: MATIC sent amount underprice",
    noSupplyLeft: "QuantArtsNFT: Mint amount is bigger than supply left",
    nonExistentToken: "ERC721Metadata: URI query for nonexistent token",
    notAddressZero: "QuantArtsNFT: Referral cannot be address zero",
    notReferralEqSender: "QuantArtsNFT: Referrer cannot be equal to msg sender -- Reason given: QuantArtsNFT: Referrer cannot be equal to msg sender.",
    minSoldSupplyNotReached: "QuantArtsNFT: Minimum sold supply is not reached",
    minSoldSupplyReached: "QuantArtsNFT: Minimum sold supply has been reached",
    arraysDifferentLength: "QuantArtsNFT: Array lengths are not equal",
    airdropAmountZero: "QuantArtsNFT: Airdrop amount is zero",
    passedWLMaxAmount: "QuantArtsNFT: Mint amount is bigger than WL max amount",
    alreadyMintWL: "QuantArtsNFT: User has already minted with WL",
    mintAmountBiggerMaxMintAmount: "QuantArtsNFT: Mint amount is bigger than WL max amount",
    notValidSign: "QuantArtsNFT: Signer is not valid",
    mintInWLPeriod: "QuantArtsNFT: Method is not WL mint -- Reason given: QuantArtsNFT: Method is not WL mint.",
    mintWLInNoWLPeriod: "QuantArtsNFT: Method is WL mint -- Reason given: QuantArtsNFT: Method is WL mint.",
    incorrectGuaranteed: "QuantArtsNFT: Incorect guaranteed timestamp",
    unitPriceLessThanMinumum: "QuantArtsNFT: UnitPrice is less than minimum",
    notMintedAnyToken: "QuantArtsNFT: User has not minted any tokens"
};